version: '3.8'

services:
  squid-proxy:
    image: ubuntu/squid:latest
    container_name: squid-proxy
    ports:
      - "3128:3128"
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
      - ./cache:/var/spool/squid
    restart: unless-stopped

  snort-ips:
    image: blacktop/snort:latest
    container_name: snort-ips
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./snort/snort.conf:/etc/snort/snort.conf
      - ./snort/rules:/etc/snort/rules
    command: snort -c /etc/snort/snort.conf -i eth0 -Q -A console
    restart: unless-stopped
